version: '3'
services:
  nginx:
   image: "nginx:alpine"
   volumes:
     - ./static:/static:ro
     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
   ports:
    - "8010:80"
   depends_on:
     - django

  django:
    build: .
    image: dzmitry/rate
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    volumes:
      - .:/app:ro
      - ./static:/app/static:rw
      - ./logs:/app/logs:rw
    depends_on:
      - postgres

  cron:
    build: ./cron
    image: dzmitry/rate-cron
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - TZ=Europe/Minsk
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DUMP_BUCKET=${DUMP_BUCKET}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT}
    volumes:
      - .:/app:ro
      - ./logs:/app/logs:rw

    depends_on:
      - django


  postgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - rate.dzmitry.psql:/var/lib/postgresql/data

volumes:
  rate.dzmitry.psql:
