version: 2
jobs:
  build:
   docker:
    - image: circleci/python:3.7
      environment:
        POSTGRES_PASSWORD: anytemppass
        DJANGO_SECRET_KEY: anytempsecretkey
        DB_HOST: localhost
    - image: circleci/postgres:9.6
      environment:
        POSTGRES_PASSWORD: anytemppass
   branches:
    only:
      - master
   steps:
    - checkout
    - restore_cache:
         name: Restore venv.
         key: python3.7-v1-{{ checksum "requirements.txt" }}

    - run:
        name: prepare env
        command: |
          python -m venv env
          . env/bin/activate
          pip install pip-tools
          pip-sync

    - save_cache:
         name: Save venv.
         key: python3.7-v1-{{ checksum "requirements.txt" }}
         paths:
          - env

    - run: |
        mkdir logs
        . env/bin/activate
        pytest

    - add_ssh_keys:
        fingerprints:
          - "45:a3:78:84:ed:6d:78:c8:85:ce:90:2f:90:60:8f:e1"
    - run:
        name: pull
        command: |
          mkdir -p ~/.ssh/
          echo '|1|X8RdkooHIKF0zlqOUc7R+hyXAT0=|G7IQk3BedSMbUE3IIz4vGwQCBhs= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFx56CIPJLfDFVY2TVyWOOMQdNk7lr5HnryrS+4zkVFrVzsZCQ06vgU3gW4Pp8YjSvd08E1fVpUxvhWm3iY1bC8=' >> ~/.ssh/known_hosts
          ssh $EC2_USER@$EC2_HOST "
            cd $EC2_PATH
            git pull
          "
    - run:
        name: restart
        command: |
          ssh $EC2_USER@$EC2_HOST "
            cd $EC2_PATH
            docker-compose up -d --build
          "

    - run:
        name: update static and db
        command: |
          ssh -tt $EC2_USER@$EC2_HOST "
            cd $EC2_PATH
            docker-compose exec django python manage.py collectstatic --noinput
            docker-compose exec django python manage.py migrate
          "


