# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_changed',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2015, 1, 1, 0, 0), verbose_name='last changed'),
            preserve_default=False,
        ),
    ]
