# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def forward(apps, schema_editor):
        UserInfo = apps.get_model('exchange', 'UserInfo')
        for u in UserInfo.objects.all():
            UserInfo.objects.filter(id=u.id).update(name=u.user.username)
        User = apps.get_model('auth', 'User')
        User.objects.filter(id__in=UserInfo.objects.all().values_list('user_id', flat=True)).delete()

    def backward(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        UserInfo = apps.get_model('exchange', 'UserInfo')
        for u in UserInfo.objects.all():
            u.user = User.objects.create(username=u.name)
            u.save()

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('exchange', '0003_auto_20160127_2353'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]

