# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_remove_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffice',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='is removed'),
        ),
    ]
