# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-12 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchangeoffice_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffice',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='exchangeoffice',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='exchangeoffice',
            name='no_coordinates',
            field=models.BooleanField(default=False, verbose_name='no coordinates'),
        ),
    ]
