# Generated by Django 2.1.1 on 2018-09-15 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0007_auto_20180912_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeoffice',
            name='users',
            field=models.ManyToManyField(related_name='exchange_offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
