# Generated by Django 2.1.1 on 2019-01-08 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_exchangeoffice_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeoffice',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='exchange_offices', to=settings.AUTH_USER_MODEL),
        ),
    ]
